# Generated by Django 5.0.6 on 2025-10-20 21:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='DPI debe contener entre 6 y 13 dígitos.', regex='^[0-9]{6,13}$')])),
                ('passport', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Teléfono con formato inválido.', regex='^[0-9+\\-() ]{6,20}$')])),
                ('origin', models.CharField(blank=True, default='', help_text='Procedencia / comunidad / municipio', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ciudadano',
                'verbose_name_plural': 'Ciudadanos',
            },
        ),
        migrations.CreateModel(
            name='VisitCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_persistente', models.CharField(db_index=True, max_length=32, unique=True)),
                ('state', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_GESTION', 'En gestión'), ('CERRADO', 'Cerrado')], db_index=True, default='ABIERTO', max_length=16)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.TextField(blank=True, default='')),
                ('last_reopen_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='visits.citizen')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='catalog.topic')),
            ],
            options={
                'verbose_name': 'Expediente de Visita',
                'verbose_name_plural': 'Expedientes de Visita',
                'unique_together': {('citizen', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('checkout_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('target_unit', models.CharField(db_index=True, max_length=128)),
                ('reason', models.CharField(blank=True, default='', max_length=256)),
                ('photo_path', models.CharField(blank=True, default='', max_length=255)),
                ('badge_code', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intake_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_visits', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visits.visitcase')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-checkin_at'],
            },
        ),
    ]
